server:  
  port: 8070
spring:  
  application:
    name: eureka-server 
 
logging:  
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'  
