 

spring:
  application:
    name: zuul-Service

zuul:
  routes:
    a:
      path: /a/test-a/**
      serviceId: MICROA-SERVICE
      stripPrefix: false
    b:
      path: /b/test-b/**
      serviceId: MICROB-SERVICE
      stripPrefix: false                         
    

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
server:
  port: 8081
