
    
server:
  port: 8073 
  
  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbplanilla
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver

error:
  message:
    formatError: Solo se admiten valores numericos.
    dataNotFound: El registro no se ha podido encontrar.
    
values:
    process:
      RSTValue: 0.10
      IsssValue: 7.5
      ConfiaValue: 7.25
      CrecerValue: 7.25
    
    format:
      dateFormat: dd/MM/yy
    
    address:
      pathFile: C:/Users/HTC-CARLOS/Desktop/DemoPlanillas/document/
      uriMicroA: http://localhost:8071/insert/


 

      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
