
    
server:
  port: 8073 
  
  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbplanilla
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver
      
      
      
    errorMessage: 
        formatError: Solo se admiten valores numericos. 
        dataNotFound: El registro no existe.
        fileNotExist: El archivo no se encuentra.
        invalidParameter: 
  
    discountsValue: 
        RSTDefault: 0.10
        isssValue: 7.5
  
    uriAndPath:
        pathFile: C:/Users/Carlos/Desktop/DemoPlanillas/document/
uriMicroA: http://localhost:8071/insert/
  
    dateFormater: 
        dateFormat: dd/MM/yy
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
