server:  
  port: 8072   


eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbpayroll
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver
      
      
error:
  message:
    EmployeeNotFound: Employee not found, parameter=
    dateNotFound: Date not found, date=
    invalidDateFormat: Date not foundtry insert format date" yyyy-MM-dd, example: 2018-03-24", date=
    payrollIdNotFound: Id Payroll not found, id=
    invalidStringFormat: Invalid String, String= 
    invalidNumberFormat: Invalid number format, number=  
    success: Exito!
