
    
server:
  port: 8073 
  
  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbplanilla
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver    
