
    
server:
  port: 8073 
  
  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbplanilla
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver

error:
  message:
    FormatError: Solo se admiten valores numericos.
    DataNotFound: El registro no se ha podido encontrar.
    FileNotFound: File not found file=
    
values:    
    format:
      dateFormat: dd/MM/yy
      fileFormat: .dat
    
    address:
      pathFile: C:/Users/HTC-CARLOS/Desktop/DemoPlanillas/document/
      uriMicroA: http://localhost:8071/payRolls/insert/


 

      
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
