
server:  
  port: 8071   



eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbpayroll
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver
  jackson: 
    date-format: dd/MM/yyyy
      

            
values:
    process:
      RSTValue: 0.10
      IsssValue: 3.0
      ConfiaValue: 7.25
      CrecerValue: 7.25
      typePayrolls: Q,q,M,m

error:
  message:
    TypePayrollNotFoundException: Type Payroll not found type=
    CompanyNotFoundException: company not found id=
    EmployeeNotFoundException: Employee not found id=
    SalaryNotFoundException: The employee's salary is invalid salary=
    Success: Exito!
        
query:
  process:
    getTotalPayroll: select count(id) from payroll where date_payroll=?
    getTotalsAcruedSalary: select sum(accrued_salary) from payroll where date_payroll=?
    getTotalsDiscountAfp: select sum(discount_afp) from payroll where date_payroll=?
    getTotalsDiscountIsss: select sum(discount_isss) from payroll where date_payroll=?
    getTotalsDiscountRent: select sum(discount_rent) from payroll where date_payroll=?
    
