
server:  
  port: 8071   


eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbplanilla
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver
            
values:
    process:
      RSTValue: 0.10
      IsssValue: 7.5
      ConfiaValue: 7.25
      CrecerValue: 7.25
