
server:  
  port: 8071   


eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  datasource:
      platform: postgres
      url: jdbc:postgresql://localhost:5432/dbpayroll
      username: postgres
      password: toor    
      driverClassName: org.postgresql.Driver
            
values:
    process:
      RSTValue: 0.10
      IsssValue: 7.5
      ConfiaValue: 7.25
      CrecerValue: 7.25
      typePayrolls: Q,q,M,m

error:
  message:
    TypePayrollNotFoundException: Type Payroll not found type= 
    CompanyNotFoundException: company not found id=
    EmployeeNotFoundException: Employee not found id=
    SalaryNotFoundException: The employee's salary is invalid salary=
    Success: Exito!
    
query:
  process:
    getAllSalarys: select sum(accrued_salary) from payroll where date_payroll=? 
